# Generated by Django 5.1 on 2024-08-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_teacher_detail_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobileno',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
    ]
