# Generated by Django 5.1 on 2024-08-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_student_mobileno_alter_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mobileno',
        ),
    ]
